# (C) 2025 GoodData Corporation
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/flight_rpc_ext.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 28, 3, "", "proto/flight_rpc_ext.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1aproto/flight_rpc_ext.proto\x1a\x1fgoogle/protobuf/timestamp.proto"\xa0\x01\n\x10\x46lightDescriptor\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32 .FlightDescriptor.DescriptorTypeR\x04type\x12\x10\n\x03\x63md\x18\x02 \x01(\x0cR\x03\x63md\x12\x12\n\x04path\x18\x03 \x03(\tR\x04path"0\n\x0e\x44\x65scriptorType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04PATH\x10\x01\x12\x07\n\x03\x43MD\x10\x02"\x94\x02\n\nFlightInfo\x12\x16\n\x06schema\x18\x01 \x01(\x0cR\x06schema\x12>\n\x11\x66light_descriptor\x18\x02 \x01(\x0b\x32\x11.FlightDescriptorR\x10\x66lightDescriptor\x12+\n\x08\x65ndpoint\x18\x03 \x03(\x0b\x32\x0f.FlightEndpointR\x08\x65ndpoint\x12#\n\rtotal_records\x18\x04 \x01(\x03R\x0ctotalRecords\x12\x1f\n\x0btotal_bytes\x18\x05 \x01(\x03R\ntotalBytes\x12\x18\n\x07ordered\x18\x06 \x01(\x08R\x07ordered\x12!\n\x0c\x61pp_metadata\x18\x07 \x01(\x0cR\x0b\x61ppMetadata"\xde\x01\n\x08PollInfo\x12\x1f\n\x04info\x18\x01 \x01(\x0b\x32\x0b.FlightInfoR\x04info\x12>\n\x11\x66light_descriptor\x18\x02 \x01(\x0b\x32\x11.FlightDescriptorR\x10\x66lightDescriptor\x12\x1f\n\x08progress\x18\x03 \x01(\x01H\x00R\x08progress\x88\x01\x01\x12\x43\n\x0f\x65xpiration_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0e\x65xpirationTimeB\x0b\n\t_progress" \n\x06Ticket\x12\x16\n\x06ticket\x18\x01 \x01(\x0cR\x06ticket"\x1c\n\x08Location\x12\x10\n\x03uri\x18\x01 \x01(\tR\x03uri"\xb0\x01\n\x0e\x46lightEndpoint\x12\x1f\n\x06ticket\x18\x01 \x01(\x0b\x32\x07.TicketR\x06ticket\x12%\n\x08location\x18\x02 \x03(\x0b\x32\t.LocationR\x08location\x12\x33\n\x0f\x65xpiration_time\x18\x03 \x01(\x0b\x32\n.TimestampR\x0e\x65xpirationTime\x12!\n\x0c\x61pp_metadata\x18\x04 \x01(\x0cR\x0b\x61ppMetadata";\n\tTimestamp\x12\x18\n\x07seconds\x18\x01 \x01(\x03R\x07seconds\x12\x14\n\x05nanos\x18\x02 \x01(\x05R\x05nanosB\x15\x42\x11\x46lightRpcExtProtoP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.flight_rpc_ext_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"B\021FlightRpcExtProtoP\001"
    _globals["_FLIGHTDESCRIPTOR"]._serialized_start = 64
    _globals["_FLIGHTDESCRIPTOR"]._serialized_end = 224
    _globals["_FLIGHTDESCRIPTOR_DESCRIPTORTYPE"]._serialized_start = 176
    _globals["_FLIGHTDESCRIPTOR_DESCRIPTORTYPE"]._serialized_end = 224
    _globals["_FLIGHTINFO"]._serialized_start = 227
    _globals["_FLIGHTINFO"]._serialized_end = 503
    _globals["_POLLINFO"]._serialized_start = 506
    _globals["_POLLINFO"]._serialized_end = 728
    _globals["_TICKET"]._serialized_start = 730
    _globals["_TICKET"]._serialized_end = 762
    _globals["_LOCATION"]._serialized_start = 764
    _globals["_LOCATION"]._serialized_end = 792
    _globals["_FLIGHTENDPOINT"]._serialized_start = 795
    _globals["_FLIGHTENDPOINT"]._serialized_end = 971
    _globals["_TIMESTAMP"]._serialized_start = 973
    _globals["_TIMESTAMP"]._serialized_end = 1032
# @@protoc_insertion_point(module_scope)
